### ISSUE TITLE
Need Aditional Maven Configuration

### ISSUE THREAD

**Issue by iscmiguelsamaniego** [openshift/openshift-jee-sample#21]
Hi needs this :

http://1004lucifer.blogspot.com/2017/06/maven-package-webxml-attribute-is.html

**Comment by bparees** [comment]
why?

`mvn clean package -Popenshift` builds it fine for me.

**Comment by victorhanxu** [comment]
I'm just learning Openshift, Any one can help? Thank you!

I can deploy this sample application to my local minishift, but when I try to deploy it to my Openshift Online account, I got an error "CrashLoopBackOff", 

log:
Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)[0m
INFO exec  java -javaagent:/opt/jboss/container/jolokia/jolokia.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError -cp "." -jar   
Error: -jar requires jar file specification
