### ISSUE TITLE
CrashLoopBackOff Issue

### ISSUE THREAD

**Issue by victorhanxu** [openshift/openshift-jee-sample#25]
I'm just learning Openshift, Any one can help? Thank you!

I can deploy this sample application to my local minishift, but when I try to deploy it to my Openshift Online account, I got an error "CrashLoopBackOff",

log:
Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)�[0m
INFO exec java -javaagent:/opt/jboss/container/jolokia/jolokia.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError -cp "." -jar
Error: -jar requires jar file specification

**Comment by ianmiell** [comment]
Try following this and let us know if it helps: 

https://containersolutions.github.io/runbooks/posts/kubernetes/crashloopbackoff/
